### ISSUE TITLE
Rebrand Quassel to Lemon

### ISSUE THREAD

**Issue by openscript** [openscript-ch/quassel#200]
- [x] All Quassel titles should be replaces with "LEMON"
- [x] Subtitle "Gather language exposure" should be replaced with "Language Exposure questionnaire for Multilinguals ONline"
- [x] Change color theme to UZH Gold
- [x] Move UZH logo from header to footer
- [x] Add kleine Weltentdecker [logo](https://www.psychologie.uzh.ch/dam/jcr:57ecbf6a-9ec5-4746-848a-065da8e76760/Logo_kleineWeltentdecker*innen) to footer
- [x] Add LEMON logo (see below) to header

**Comment by openscript** [comment]
@stwerm Should we also change the color theme to a more lemon like color? I suggest choosing one from the corporate colors:

https://www.cd.uzh.ch/dam/jcr:ceea0afd-0f51-442c-b4ca-c49bb6bd1220/uzh-corporate-colors-rgb.pdf

**Comment by stwerm** [comment]
Great idea, we suggest to go with "UZH Gold"

**Comment by openscript** [comment]
@stwerm Adding the kleine Weltentdecker logo would also fit into this task:

![image](https://github.com/user-attachments/assets/e0a596cf-713c-4c0c-82bc-4b33eb91c8ef)

1. Should we move the UZH Logo from 1 to 2?
2. Should we add the kleine Weltentdecker logo at 1? Do you have a .svg version of the logo that you can send us?

**Comment by stwerm** [comment]
1. yes
2. we suggest to put the uzh and the kleine weltentdecker*innen logo at 2 and put the lemon logo at 1
![lemon5-green_leave](https://github.com/user-attachments/assets/2dace43a-6f9e-4eec-a88f-fa0a1a849862)
